### ISSUE TITLE
Add Game Mode Selection for More Targeted User Searches

### ISSUE THREAD

**Issue by audio-spec** [sibyl666/osu-mutual-finder#3]
Hey, I wanted to say that this project is pretty cool, and would like to request a new feature.

Would it be possible to implement some kind of dropdown select to target searching for mutuals from a particular game mode?

Would mean making this URL in Mutuals.vue dynamic:

`await axios.get("https://osu.ppy.sh/rankings/osu/performance")`

Standard - https://osu.ppy.sh/rankings/osu/performance
Taiko - https://osu.ppy.sh/rankings/taiko/performance
Catch - https://osu.ppy.sh/rankings/fruits/performance
Mania - https://osu.ppy.sh/rankings/mania/performance

**Comment by sibyl666** [comment]
This should be easy. Probably I will work on this today. Thanks!

**Comment by sibyl666** [comment]
I released this feature with version [1.2.4](https://github.com/sibyl666/osu-mutual-finder/releases/tag/v1.2.4). When you open the app it should update itself

**Comment by audio-spec** [comment]
Cool, thanks! :)
