### ISSUE TITLE
Extend Country to Check Options from Settings

### ISSUE THREAD

**Issue by audio-spec** [sibyl666/osu-mutual-finder#7]
Hello, I have another enhancement request for this project.

Currently it appears you can only select from the top 50 countries to search as per this page - https://osu.ppy.sh/rankings/osu/country

For completeness, I was wondering if the country select could be extended to include others that are on page 2, page 3, and so on... or if it could be possible to manually enter the code for those other options? Thanks!

**Comment by sibyl666** [comment]
It should already do that. If it doesn't work I will look into that today

**Comment by sibyl666** [comment]
It should already do that. If it doesn't work I will look into that today

**Comment by sibyl666** [comment]
The problem is that I have to make a request to that webpage which I am trying to keep minimal because I don't use the osu! api. I will probably just hardcode these countries to the app. I will probably look into it.

**Comment by sibyl666** [comment]
This should work now as you want with the version 1.2.5 release. If It doesn't then you can open the issue again. Thanks!

**Comment by audio-spec** [comment]
Yea, I think hard-coding would be most effective as long as osu! web doesn't change those country codes 🙂 

Works good so far. Just noticed a minor visual defect where "Found mutuals" now says "Checked".

**Comment by sibyl666** [comment]
Opssss yea you are right. Since It's not that important I will probably fix that later.
